### ISSUE TITLE
png convert issue?

### ISSUE THREAD

**Issue by fourroses666** [mplavala/webpconverter#9] opened 2022-04-29 11:02 UTC
« Evolution CMS Parse Error »

`Error : imagecreatefrompng(): gd-png: libpng warning: Interlace handling should be turned on when using png_read_image`

Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /x/domains/x.nl/public_html/assets/plugins/webpconverter/plugin.webpconverter.php
Line | 157
Source | $image =  imagecreatefrompng($srcServerFile);

----

Any idea what could be wrong? Some server setting?

EVO version 3.1.10
PHP version 7.4.28

**Comment by mplavala** [comment] 2022-04-29 12:09
Hi, this is a combination of problems in dependencies of PHP, which was fixed very recently, see here https://bugs.php.net/bug.php?id=71316
Also, according to what I found online, the problem might be fixed by opening the image in Photoshop/Gimp and resaving it, or resaving it as PNG-8.

Let me know if resaving the image helps.

**Comment by fourroses666** [comment] 2022-04-29 12:34
Re-saving the .png didn't solve it..
I did found the issue. It looks like Phpthumb generates the wrong format .png :-o

```<img src="[!phpthumb? &input=`[+tv.thumbnail+]` &options=`w=680,h=420,zc=1`!]" alt="[+description+]" />```

I can show the PNG but when I use phpthumb on the same image it throws the error so I think we need to look at phpthumb (installed it by Extras)

**Closed as completed** 2022-04-29 12:36 UTC

**Comment by mplavala** [comment] 2022-04-29 14:38
This is strange, because phpThumb uses just buil-in PHP functions to generate the smaller image. This can be some weird coincidence on your server, but I will try to look out for similar problems.

If it helps, you can use `data-webpconverter-exclude="on"` to exclude that one image from being processed by WebP Converter.

**Comment by fourroses666** [comment] 2022-04-29 14:54
I have converted the image to jpg because png was not needed.

Tested on the same server + php version and other domain but also the same issue. 
Didn't test on an other host.

Its not the image size. Tested with an other image (png) and same result.

_If you would like to see it in action I can give you access._

**Comment by fourroses666** [comment] 2022-04-29 14:58
without <img tag the image is being converted like it should:
```[!phpthumb? &input=`/theme/img/test2.png` &options=`w=680,h=680,zc=1`!]```

assets/cache/images/theme/img/test2-680x680-58f.png

**Comment by mplavala** [comment] 2022-04-29 15:06
> I have converted the image to jpg because png was not needed.

This then (very likely) means that the problem is not in the original image, but with the version generated by phpThumb. This is very odd, maybe try contacting the hosting and ask them whether they are getting some errors.

> without <img tag the image is being converted like it should:

Because without the `<img ... >` tag WebP Converter does not see the image and does not try to do anything with it.

**Comment by fourroses666** [comment] 2022-05-02 08:42
Its my own VPS. Guess something goes wrong indeed with the 'Interlace handling' which isn't on on my server. Will deal with it if I see more of these errors on other sites.
